import '../assets/icons/style.css'
import '../assets/css/styles.css'
import '../assets/css/app.css'
import '../assets/css/login.css'
import '../assets/css/sidebar.css'
import '../assets/css/header.css'
import '../assets/css/userSession.css'
import '../assets/css/formRegistro.css'
import '../assets/css/paginacion.css'

import '../assets/css/ui/table.css'
import '../assets/css/ui/switch.css'
import '../assets/css/ui/dropdown.css'
import '../assets/css/ui/notify.css'
import '../assets/css/ui/loading.css'
import '../assets/css/ui/empty.css'

import '../assets/css/common.css'
import '../assets/css/print.css'